name: Flux Manage Issues

on:
  issues:
    types: [opened]

jobs:
  manage-issues:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Label KoiosBot
        if: contains(github.event.issue.title, "KoiosBot")
        uses: actions-cool/issues-helper@v2.0.0
        with:
          actions: 'update-issue'
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.issue.number }}
          labels: ''
          assignees: 'Hagfog'
      - name: Label WordBot
        if: contains(github.event.issue.title, "WordBot") || contains(github.event.issue.title, "WB")
        uses: actions-cool/issues-helper@v2.0.0
        with:
          actions: 'update-issue'
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.issue.number }}
          labels: ''
          assignees: 'ysfchn,Zamion101'  
      - name: Fallback if no one has assigned
        if: ${{ !success() }}
        uses: actions-cool/issues-helper@v2.0.0
        with:
          actions: 'update-issue'
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.issue.number }}
          labels: 'CHECK'
          assignees: 'Teo00'
