name: Flux Manage Issues

on:
  issues:
    types: [opened]

jobs:
  manage-issues:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Check for KoiosBot
        id: koiosbot
        if: ${{ contains(github.event.issue.title, 'KoiosBot') }}
        uses: actions-cool/issues-helper@v2.0.0
        with:
          actions: 'update-issue'
          update-mode: 'append'
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.issue.number }}
          labels: 'CHECK'
          assignees: 'Hagfog'
      - name: Check for WordBot
        id: wordbot
        if: ${{ contains(github.event.issue.title, 'WordBot') || contains(github.event.issue.title, 'WB') }}
        uses: actions-cool/issues-helper@v2.0.0
        with:
          actions: 'update-issue'
          update-mode: 'append'
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.issue.number }}
          labels: 'CHECK'
          assignees: 'ysfchn,Zamion101'  
      - name: Fallback
        if: (${{ steps.koiosbot.conclusion }} == 'skipped' && ${{ steps.wordbot.conclusion }} == 'skipped')
        uses: actions-cool/issues-helper@v2.0.0
        with:
          actions: 'update-issue'
          update-mode: 'append'
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.issue.number }}
          labels: 'CHECK'
          assignees: 'Teo00'
